name: Create envfile

on: [ push ]

jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_DEBUG: false
        envkey_KV_URL: ${{ vars.KV_URL }}
        envkey_KV_REST_API_URL: ${{ vars.KV_REST_API_URL }}
        envkey_KV_REST_API_TOKEN: ${{ vars.KV_REST_API_TOKEN }}
        envkey_KV_REST_API_READ_ONLY_TOKEN: ${{ vars.KV_REST_API_READ_ONLY_TOKEN }}
        envkey_VITE_KV_URL: ${{ vars.VITE_KV_URL }}
        envkey_VITE_KV_REST_API_URL: ${{ vars.VITE_KV_REST_API_URL }}
        envkey_VITE_KV_REST_API_TOKEN: ${{ vars.VITE_KV_REST_API_TOKEN }}
        envkey_VITE_KV_REST_API_READ_ONLY_TOKEN: ${{ vars.VITE_KV_REST_API_READ_ONLY_TOKEN }}
        envkey_UPSTASH_DISABLE_TELEMETRY: ${{ vars.UPSTASH_DISABLE_TELEMETRY }}
        file_name: .env
        fail_on_empty: false
        sort_keys: false